//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton2018.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epidemiolog
    {
        public int Id { get; set; }
        public string Licni_Broj { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Lozinka { get; set; }
    }
}
