//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton2018.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grad
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public double Lokacija_X { get; set; }
        public double Lokacija_Y { get; set; }
        public Nullable<int> DrzavaId { get; set; }
        public Nullable<long> Broj_Stanovnika { get; set; }
    
        public virtual Drzava Drzava { get; set; }
    }
}
