//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton2018.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instanca_Bolesti
    {
        public int Id { get; set; }
        public float Lokacija_X { get; set; }
        public float Lokacija_Y { get; set; }
        public string Pol { get; set; }
        public int Starost { get; set; }
        public System.DateTime Otkrivena { get; set; }
        public System.DateTime Prijavljenja { get; set; }
        public System.DateTime Okoncana { get; set; }
        public bool Smrtni_Ishod { get; set; }
        public bool Terapija { get; set; }
        public string Opis_Pojave { get; set; }
        public int Bolest_Id { get; set; }
    
        public virtual Bolest Bolest { get; set; }
    }
}
