//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton2018.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A42552_ArxyaArsaEntities : DbContext
    {
        public DB_A42552_ArxyaArsaEntities()
            : base("name=DB_A42552_ArxyaArsaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolest> Bolest { get; set; }
        public virtual DbSet<Drzava> Drzava { get; set; }
        public virtual DbSet<Epidemiolog> Epidemiolog { get; set; }
        public virtual DbSet<Grad> Grad { get; set; }
        public virtual DbSet<Instanca_Bolesti> Instanca_Bolesti { get; set; }
        public virtual DbSet<Period_Javljanja> Period_Javljanja { get; set; }
    }
}
