//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakaton2018.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period_Javljanja
    {
        public int Id { get; set; }
        public System.DateTime Pocetak { get; set; }
        public System.DateTime Kraj { get; set; }
        public int Bolest_Id { get; set; }
    
        public virtual Bolest Bolest { get; set; }
    }
}
